version: 1.0.{build}
image: Visual Studio 2013
configuration: Release
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake -G "Visual Studio 12" ..
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: build\release\mplus.exe
  name: MPlus